---
- name: Test failover and failback of bonding interface
  hosts: db01
  become: yes
  tasks:
    - name: Gather facts about bond interfaces
      ansible.builtin.setup:
        filter: ansible_net_bonding

    - name: Get active and backup slave interfaces
      set_fact:
        active_slave: "{{ item.value.active_slave }}"
        backup_slaves: "{{ item.value.slaves | difference([item.value.active_slave]) }}"
      loop: "{{ ansible_facts.ansible_net_bonding | dict2items }}"
      when: "'bond' in item.key"

    - name: Show active and backup slave interfaces
      debug:
        var: (active_slave, backup_slaves)

    - name: Set active slave interface to down
      ansible.builtin.command: "ip link set {{ active_slave }} down"
      register: result
      changed_when: False

    - name: Wait for 10 seconds for failover
      ansible.builtin.pause:
        seconds: 10

    - name: Ping test after failover
      ansible.builtin.ping:

    - name: Set the original active slave interface back to up
      ansible.builtin.command: "ip link set {{ active_slave }} up"
      register: result
      changed_when: False

    - name: Wait for 10 seconds for failback
      ansible.builtin.pause:
        seconds: 10

    - name: Ping test after failback
      ansible.builtin.ping:

    - name: Gather facts about bond interfaces after failback
      ansible.builtin.setup:
        filter: ansible_net_bonding

    - name: Get active and backup slave interfaces after failback
      set_fact:
        active_slave_after_failback: "{{ item.value.active_slave }}"
        backup_slaves_after_failback: "{{ item.value.slaves | difference([item.value.active_slave]) }}"
      loop: "{{ ansible_facts.ansible_net_bonding | dict2items }}"
      when: "'bond' in item.key"

    - name: Show active and backup slave interfaces after failback
      debug:
        var: (active_slave_after_failback, backup_slaves_after_failback)

    - name: Check if failback occurred successfully
      assert:
        that:
          - "active_slave == active_slave_after_failback"
        fail_msg: "Failback test failed"
        success_msg: "Failback test succeeded"
...

