---
- hosts: all
  become: yes
  tasks:

  - name: create file name test.txt
    file:
      path: /tmp/test.txt
      state: touch
      mode: 0777
      owner: root
      group: root
  - name: create directory name testdir
    file:
      path: /tmp/testdir
      state: directory
      mode: 0777
      owner: root
      group: root

