---
- hosts: db01
  become: yes
  tasks:
  - name: add line if it doesn't exist.
    lineinfile:
      path: /etc/postfix/main.cf
    # string to search
      regexp: "html_directory = no"
    # the string to replace
      line: "html_direcstory = yes "
      state: present
      backup: yes
