- name: Pre-Upgrade Check for RHEL 7.9 to 8.6 using Leap
  hosts: RHEL.example.com
  become: yes

  tasks:
  - name: Install leap package
    package:
      name: leapp
      state: present

  - name: Run pre-upgrade check with Leap
    command: leapp pre-upgrade
    register: pre_upgrade_result

  - name: Display pre-upgrade check results
    debug:
      var: pre_upgrade_result.stdout_lines

